In [34]:
import pandas as pd

In [35]:
# url link to the csv file for importing college scorecard data
url = 'https://ed-public-download.app.cloud.gov/downloads/Most-Recent-Cohorts-All-Data-Elements.csv'

In [36]:
# url link to the csv file for importing earnings data
url1 = 'https://ed-public-download.app.cloud.gov/downloads/Most-Recent-Cohorts-Treasury-Elements.csv'

In [4]:
# Several values in the columns are represented as PrivacySuppressed: replacing them with NULL
df = pd.read_csv(url, na_values=['PrivacySuppressed'])

/Users/julie/anaconda/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2902: DtypeWarning: Columns (6,9,1729,1743) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [21]:
### did a curl -O on the URL to download locally, your was is fine too.

In [38]:
df = pd.read_csv('Most-Recent-Cohorts-All-Data-Elements.csv',na_values=['PrivacySuppressed'])

/Users/julie/anaconda/lib/python3.5/site-packages/IPython/core/interactiveshell.py:2902: DtypeWarning: Columns (6,9,1729,1743) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [54]:
### I was getting a bunch of what looked like unicode characters in the first column name, so changed it to just be
### UNITID.  For whatever reason, you may not have to have done this.

In [49]:
df.rename(columns={df.columns[0]:'UNITID'},inplace=True)

In [51]:
#UNITID can be used as he index since it has a unique value for each school
#We developed a separate table using UNITID, name, city and state since these can only be used to identify school
schools = df[['UNITID', 'INSTNM', 'CITY', 'STABBR']]

In [53]:
schools.head()

   UNITID                               INSTNM        CITY STABBR
0  100654             Alabama A & M University      Normal     AL
1  100663  University of Alabama at Birmingham  Birmingham     AL
2  100690                   Amridge University  Montgomery     AL
3  100706  University of Alabama in Huntsville  Huntsville     AL
4  100724             Alabama State University  Montgomery     AL

In [55]:
#Deleting the columns that cant be used for model development: Zip, lat, long, opeid, opeid6, accreditor, school_url, price-calculator_url, repayment_date.median
#separation_date.median, alias, accreditor_code, title_iv.approval_date
other_columns = ['INSTNM', 'CITY','STABBR','OPEID', 'OPEID6', 'ZIP','ACCREDAGENCY','LATITUDE', 'LONGITUDE', 'INSTURL','NPCURL','REPAY_DT_MDN','SEPAR_DT_MDN','ACCREDCODE','T4APPROVALDATE']

In [56]:
df.drop(other_columns, axis = 1, inplace =True)

In [57]:
df.shape

(7593, 1790)

In [58]:
df.head()

,UNITID,SCH_DEG,HCM2,MAIN,NUMBRANCH,PREDDEG,HIGHDEG,CONTROL,ST_FIPS,REGION,...,OMENRYP8_FTNFT,OMENRAP8_FTNFT,OMENRUP8_FTNFT,OMACHT6_PTNFT,OMAWDP6_PTNFT,OMACHT8_PTNFT,OMAWDP8_PTNFT,OMENRYP8_PTNFT,OMENRAP8_PTNFT,OMENRUP8_PTNFT
0,100654,3.0,0,1,1,3,4,1,1,5,...,0.0000,0.1727,0.3909,16.0,0.3125,16.0,0.3125,0.0000,0.0000,0.6875
1,100663,3.0,0,1,1,3,4,1,1,5,...,0.0102,0.2187,0.1385,248.0,0.3589,248.0,0.4032,0.0444,0.2500,0.3024
2,100690,3.0,0,1,1,3,4,2,1,5,...,0.0125,0.4375,0.0000,36.0,0.5000,36.0,0.5278,0.0278,0.4444,0.0000
3,100706,3.0,0,1,1,3,4,1,1,5,...,0.0124,0.3209,0.1242,131.0,0.3588,131.0,0.3664,0.0382,0.4351,0.1603
4,100724,3.0,0,1,1,3,4,1,1,5,...,0.0000,0.3672,0.1977,36.0,0.2778,36.0,0.3056,0.0278,0.5833,0.0833

In [59]:
# getting earnings data from the csv file Most-Recent-Cohorts-Treasury-Elements.csv
df_earnings = pd.read_csv(url1)

In [65]:
df_earnings.rename(columns={df_earnings.columns[0]:'UNITID'},inplace=True)

In [66]:
df_earnings.head()

,UNITID,OPEID,OPEID6,INSTNM,COUNT_ED,AGEGE24,PCT_WHITE,PCT_BLACK,PCT_ASIAN,PCT_HISPANIC,...,PCT25_EARN_WNE_P8,PCT75_EARN_WNE_P8,PCT90_EARN_WNE_P8,SD_EARN_WNE_P8,GT_25K_P8,COUNT_NWNE_P9,COUNT_WNE_P9,MN_EARN_WNE_P9,SD_EARN_WNE_P9,GT_25K_P9
0,100654,100200,1002,Alabama A & M University,NaN,0.07999999821186,46.8400001525878,47.9799995422363,1.48000001907348,3.78999996185302,...,15100,38700,60700,21500,0.544,215,1480,33800,27500,0.58783781528472
1,100663,105200,1052,University of Alabama at Birmingham,NaN,0.25999999046325,69.0199966430664,27.7600002288818,1.10000002384185,2.02999997138977,...,23300,52600,74700,36700,0.722,347,2592,44500,38600,0.73726850748062
2,100690,2503400,25034,Amridge University,NaN,0.82999998331069,70.8799972534179,22.5300006866455,1.28999996185302,6.94000005722046,...,18400,52200,78700,30500,0.668,41,174,42400,30500,0.7356321811676
3,100706,105500,1055,University of Alabama in Huntsville,NaN,0.28999999165534,76.3799972534179,18.9799995422363,1.41999995708465,2.54999995231628,...,23300,62100,80700,27600,0.73,152,1106,50200,37700,0.78119349479675
4,100724,100500,1005,Alabama State University,NaN,0.10999999940395,42.6899986267089,52.3199996948242,1.40999996662139,4.09000015258789,...,13800,35700,48400,17300,0.468,297,1810,29400,20000,0.52983427047729

In [67]:
# separating UNITID and MEDIAN_HH_INC, since MEDIAN_HH_INC will be predicted using other variables and UNITID will be used as index
# also separating OPEID and OPEID 6 since they have been already dropped from the main table
df_earnings.drop(['UNITID','OPEID','OPEID6','INSTNM','MEDIAN_HH_INC'], axis=1, inplace=True)

In [68]:
#The main file consists of all the fields so removing earnings columns from the main data except MEDIAN_HH_INC
df.drop(df_earnings.columns, axis=1, inplace = True)

In [69]:
df.shape

(7593, 1706)

In [70]:
# checking head of the data
df.head()

,UNITID,SCH_DEG,HCM2,MAIN,NUMBRANCH,PREDDEG,HIGHDEG,CONTROL,ST_FIPS,REGION,...,OMENRYP8_FTNFT,OMENRAP8_FTNFT,OMENRUP8_FTNFT,OMACHT6_PTNFT,OMAWDP6_PTNFT,OMACHT8_PTNFT,OMAWDP8_PTNFT,OMENRYP8_PTNFT,OMENRAP8_PTNFT,OMENRUP8_PTNFT
0,100654,3.0,0,1,1,3,4,1,1,5,...,0.0000,0.1727,0.3909,16.0,0.3125,16.0,0.3125,0.0000,0.0000,0.6875
1,100663,3.0,0,1,1,3,4,1,1,5,...,0.0102,0.2187,0.1385,248.0,0.3589,248.0,0.4032,0.0444,0.2500,0.3024
2,100690,3.0,0,1,1,3,4,2,1,5,...,0.0125,0.4375,0.0000,36.0,0.5000,36.0,0.5278,0.0278,0.4444,0.0000
3,100706,3.0,0,1,1,3,4,1,1,5,...,0.0124,0.3209,0.1242,131.0,0.3588,131.0,0.3664,0.0382,0.4351,0.1603
4,100724,3.0,0,1,1,3,4,1,1,5,...,0.0000,0.3672,0.1977,36.0,0.2778,36.0,0.3056,0.0278,0.5833,0.0833

In [71]:
# visually inspecting the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7593 entries, 0 to 7592
Columns: 1706 entries, UNITID to OMENRUP8_PTNFT
dtypes: float64(1694), int64(11), object(1)
memory usage: 98.8+ MB

In [72]:
df.describe()

/Users/julie/anaconda/lib/python3.5/site-packages/numpy/lib/function_base.py:4274: RuntimeWarning: Invalid value encountered in percentile
  interpolation=interpolation)

,UNITID,SCH_DEG,HCM2,MAIN,NUMBRANCH,PREDDEG,HIGHDEG,CONTROL,ST_FIPS,REGION,...,OMENRYP8_FTNFT,OMENRAP8_FTNFT,OMENRUP8_FTNFT,OMACHT6_PTNFT,OMAWDP6_PTNFT,OMACHT8_PTNFT,OMAWDP8_PTNFT,OMENRYP8_PTNFT,OMENRAP8_PTNFT,OMENRUP8_PTNFT
count,7.593000e+03,7286.00000,7593.000000,7593.000000,7593.000000,7593.000000,7593.000000,7593.000000,7593.000000,7593.000000,...,3671.000000,3671.000000,3671.000000,3955.000000,2948.000000,3955.000000,2947.000000,2947.000000,2947.000000,2947.000000
mean,1.765726e+06,1.89720,0.009219,0.738312,7.185566,1.810088,2.202292,2.192282,29.079020,4.613723,...,0.008412,0.169805,0.260487,158.747914,0.368262,158.705689,0.386980,0.016495,0.207125,0.389400
std,6.771661e+06,0.87879,0.095578,0.439583,21.184166,1.031903,1.318152,0.835941,16.679116,2.167087,...,0.035949,0.175972,0.206629,701.589333,0.234315,701.556552,0.235768,0.054862,0.209142,0.251564
min,1.006540e+05,1.00000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.752630e+05,NaN,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,13.000000,3.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2.318730e+05,NaN,0.000000,1.000000,1.000000,2.000000,2.000000,2.000000,29.000000,5.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,4.496120e+05,NaN,0.000000,1.000000,3.000000,3.000000,4.000000,3.000000,42.000000,6.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,4.862110e+07,3.00000,1.000000,1.000000,135.000000,4.000000,4.000000,3.000000,78.000000,9.000000,...,0.940300,1.000000,1.000000,33078.000000,1.000000,33078.000000,1.000000,1.000000,1.000000,1.000000

In [73]:
df.set_index('UNITID', inplace=True)

In [74]:
df.head()

,SCH_DEG,HCM2,MAIN,NUMBRANCH,PREDDEG,HIGHDEG,CONTROL,ST_FIPS,REGION,LOCALE,...,OMENRYP8_FTNFT,OMENRAP8_FTNFT,OMENRUP8_FTNFT,OMACHT6_PTNFT,OMAWDP6_PTNFT,OMACHT8_PTNFT,OMAWDP8_PTNFT,OMENRYP8_PTNFT,OMENRAP8_PTNFT,OMENRUP8_PTNFT
UNITID,,,,,,,,,,,,,,,,,,,,,
100654,3.0,0,1,1,3,4,1,1,5,12.0,...,0.0000,0.1727,0.3909,16.0,0.3125,16.0,0.3125,0.0000,0.0000,0.6875
100663,3.0,0,1,1,3,4,1,1,5,12.0,...,0.0102,0.2187,0.1385,248.0,0.3589,248.0,0.4032,0.0444,0.2500,0.3024
100690,3.0,0,1,1,3,4,2,1,5,12.0,...,0.0125,0.4375,0.0000,36.0,0.5000,36.0,0.5278,0.0278,0.4444,0.0000
100706,3.0,0,1,1,3,4,1,1,5,12.0,...,0.0124,0.3209,0.1242,131.0,0.3588,131.0,0.3664,0.0382,0.4351,0.1603
100724,3.0,0,1,1,3,4,1,1,5,12.0,...,0.0000,0.3672,0.1977,36.0,0.2778,36.0,0.3056,0.0278,0.5833,0.0833

In [75]:
#checking for columns with less than 40 percent of null data
columns = df.isnull().sum()/df.shape[0]*100 < 40

In [76]:
df1 = df.loc[:,columns]

In [77]:
df1.head()

,SCH_DEG,HCM2,MAIN,NUMBRANCH,PREDDEG,HIGHDEG,CONTROL,ST_FIPS,REGION,LOCALE,...,MALE_RPY_3YR_RT_SUPP,FIRSTGEN_RPY_3YR_RT_SUPP,NOTFIRSTGEN_RPY_3YR_RT_SUPP,ICLEVEL,UGDS_MEN,UGDS_WOMEN,CDR3_DENOM,CDR2_DENOM,D_PCTPELL_PCTFLOAN,OPENADMP
UNITID,,,,,,,,,,,,,,,,,,,,,
100654,3.0,0,1,1,3,4,1,1,5,12.0,...,0.245985,0.237633,0.251324,1,0.4617,0.5383,1812.0,1574.0,4210.0,2.0
100663,3.0,0,1,1,3,4,1,1,5,12.0,...,0.541336,0.511099,0.525161,1,0.4116,0.5884,4159.0,3481.0,11679.0,2.0
100690,3.0,0,1,1,3,4,2,1,5,12.0,...,0.306250,0.224880,0.240909,1,0.4286,0.5714,380.0,336.0,279.0,1.0
100706,3.0,0,1,1,3,4,1,1,5,12.0,...,0.594189,0.515263,0.566970,1,0.5740,0.4260,1464.0,1392.0,5618.0,2.0
100724,3.0,0,1,1,3,4,1,1,5,12.0,...,0.175749,0.191638,0.199895,1,0.3850,0.6150,2196.0,1961.0,4805.0,2.0

In [78]:
import numpy as np

In [79]:
#checking for nan values
np.where(np.isnan(df1))

(array([   2,    2,    2, ..., 7592, 7592, 7592]),
 array([289, 291, 292, ..., 594, 595, 596]))

In [80]:
#filling the null data with mean
df1.fillna(df1.mean(), inplace=True).head()

/Users/julie/anaconda/lib/python3.5/site-packages/pandas/core/generic.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

,SCH_DEG,HCM2,MAIN,NUMBRANCH,PREDDEG,HIGHDEG,CONTROL,ST_FIPS,REGION,LOCALE,...,MALE_RPY_3YR_RT_SUPP,FIRSTGEN_RPY_3YR_RT_SUPP,NOTFIRSTGEN_RPY_3YR_RT_SUPP,ICLEVEL,UGDS_MEN,UGDS_WOMEN,CDR3_DENOM,CDR2_DENOM,D_PCTPELL_PCTFLOAN,OPENADMP
UNITID,,,,,,,,,,,,,,,,,,,,,
100654,3.0,0,1,1,3,4,1,1,5,12.0,...,0.245985,0.237633,0.251324,1,0.4617,0.5383,1812.0,1574.0,4210.0,2.0
100663,3.0,0,1,1,3,4,1,1,5,12.0,...,0.541336,0.511099,0.525161,1,0.4116,0.5884,4159.0,3481.0,11679.0,2.0
100690,3.0,0,1,1,3,4,2,1,5,12.0,...,0.306250,0.224880,0.240909,1,0.4286,0.5714,380.0,336.0,279.0,1.0
100706,3.0,0,1,1,3,4,1,1,5,12.0,...,0.594189,0.515263,0.566970,1,0.5740,0.4260,1464.0,1392.0,5618.0,2.0
100724,3.0,0,1,1,3,4,1,1,5,12.0,...,0.175749,0.191638,0.199895,1,0.3850,0.6150,2196.0,1961.0,4805.0,2.0

In [81]:
from sklearn.feature_selection import SelectFromModel

In [82]:
y = df1['MEDIAN_HH_INC']

In [83]:
X = df1.drop('MEDIAN_HH_INC', axis=1)

In [101]:
from sklearn.ensemble import RandomForestRegressor
clf = RandomForestRegressor()

In [119]:
sfm = SelectFromModel(clf, threshold=0.005)
sfm.fit(X, y)
n_features = sfm.transform(X).shape[1]
features = sfm.transform(X)

In [120]:
n_features

20

In [121]:
type(features)

numpy.ndarray

In [122]:
sfm.get_support(indices=True)

array([  7,   8,   9, 255, 256, 264, 265, 268, 271, 272, 273, 275, 277,
       279, 359, 371, 389, 396, 397, 570])

In [130]:
type(X.columns)

pandas.indexes.base.Index

In [ ]:
### dataframe with just features that have a feature importance > .005 in the random forrest

In [133]:
df1.iloc[:,sfm.get_support(indices=True)]

,ST_FIPS,REGION,LOCALE,UGDS_HISP,UGDS_ASIAN,UGDS_API,UGDS_AIANOLD,UG_UNKN,UG_API,UG_AIANOLD,UG_HISPOLD,PPTUG_EF2,TUITFTE,PCTPELL,RPY_5YR_RT,RPY_7YR_RT,INC_PCT_H2,APPL_SCH_PCT_GE5,DEP_INC_AVG,FAMINC
UNITID,,,,,,,,,,,,,,,,,,,,
100654,1,5,12.000000,0.005800,0.00180,0.002500,0.002000,0.001400,0.003000,0.002700,0.002700,0.078100,9657.00000,0.724900,0.327986,0.381349,0.037935,0.347383,33295.637228,30489.792062
100663,1,5,12.000000,0.031700,0.05950,0.041900,0.004800,0.026600,0.028600,0.003100,0.010100,0.316200,10263.00000,0.350500,0.577946,0.633904,0.120943,0.107236,60411.664060,50315.256601
100690,1,5,12.000000,0.019500,0.00000,0.012900,0.002600,0.000000,0.020400,0.000000,0.061200,0.673500,17071.00000,0.745500,0.394231,0.468531,0.096644,0.109890,25829.656250,19593.146520
100706,1,5,12.000000,0.041700,0.03810,0.029000,0.017000,0.048700,0.036600,0.020500,0.018600,0.390600,8917.00000,0.317900,0.581463,0.637479,0.162374,0.089696,68369.367666,55624.221251
100724,1,5,12.000000,0.011600,0.00320,0.000000,0.000000,0.031300,0.001800,0.000500,0.002800,0.170400,7717.00000,0.756700,0.265860,0.318300,0.039775,0.278023,34650.751743,30857.277220
100751,1,5,13.000000,0.039900,0.01130,0.011100,0.005700,0.000000,0.010500,0.006100,0.008600,0.101400,13373.00000,0.200900,0.631207,0.704680,0.322584,0.196764,99525.253267,89976.373415
100760,1,5,32.000000,0.012300,0.00450,0.000000,0.000000,0.001300,0.003800,0.005100,0.004400,0.397600,2548.00000,0.555400,0.345511,0.420024,0.025350,0.102273,34678.516556,28175.277098
100812,1,5,31.000000,0.018900,0.00620,0.000000,0.000000,0.016200,0.005600,0.016500,0.003800,0.595800,6189.00000,0.423300,0.531312,0.598741,0.053171,0.042281,58970.547297,38704.585522
100830,1,5,12.000000,0.007000,0.02410,0.015600,0.004900,0.006800,0.017800,0.004600,0.011200,0.359700,8039.00000,0.437300,0.481514,0.531396,0.065874,0.146386,44217.987069,38489.309241
100858,1,5,13.000000,0.032300,0.02500,0.018200,0.006400,0.001400,0.011600,0.004700,0.008300,0.113700,14724.00000,0.163100,0.778889,0.803736,0.316202,0.120832,95514.849097,88987.814633
100937,1,5,12.000000,0.020800,0.05350,0.041100,0.006000,0.002900,0.035800,0.006500,0.005000,0.045200,10473.00000,0.199200,0.742466,0.781690,0.282222,0.402222,90447.104545,88553.800000
101028,1,5,41.000000,0.045300,0.01090,0.000000,0.000000,0.021200,0.010900,0.003400,0.030300,0.552600,1829.00000,0.605000,0.400438,0.398148,0.012775,0.130589,30878.890157,26331.860185
101073,1,5,32.000000,0.031700,0.00260,0.001800,0.000000,0.000000,0.000000,0.000000,0.000000,0.191700,11534.00000,0.904800,0.176471,0.157143,0.096644,0.314342,22727.373494,19597.532417
101116,1,5,12.000000,0.021700,0.01520,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.304300,14158.00000,0.692200,0.262366,0.353744,0.034024,0.057478,39044.258671,27871.073254
101143,1,5,32.000000,0.058200,0.02160,0.000000,0.000000,0.017000,0.028900,0.011300,0.033300,0.455300,2188.00000,0.492800,0.456022,0.561772,0.025274,0.090986,35264.827035,27881.847515
101161,1,5,32.000000,0.034100,0.00890,0.000000,0.000000,0.003200,0.005400,0.009700,0.005800,0.393500,2556.00000,0.463400,0.424747,0.500396,0.050241,0.117329,41063.111319,34208.380866
101189,1,5,12.000000,0.024100,0.00260,0.003000,0.004500,0.008200,0.006500,0.009800,0.013100,0.295800,11020.00000,0.559600,0.408964,0.469421,0.057496,0.156368,52021.204216,35837.879097
101240,1,5,13.000000,0.030800,0.00460,0.000000,0.000000,0.003300,0.003800,0.005600,0.007900,0.448700,990.00000,0.560400,0.476760,0.541833,0.096644,0.069085,22315.005181,18185.034888
101277,1,5,32.000000,0.098900,0.00000,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,6329.00000,0.670700,0.476760,0.541833,0.096644,0.132706,35786.608696,26344.592593
101286,1,5,41.000000,0.026800,0.00650,0.000000,0.000000,0.007200,0.010200,0.004400,0.010800,0.379000,2034.00000,0.539800,0.476760,0.541833,0.096644,0.057462,21195.060741,18208.369114
101295,1,5,32.000000,0.038000,0.00730,0.003500,0.009500,0.000000,0.003000,0.002800,0.003600,0.456600,2884.00000,0.498200,0.483081,0.496477,0.037337,0.065339,43227.243448,34933.664904
101301,1,5,32.000000,0.007200,0.00290,0.000000,0.000000,0.000700,0.004200,0.000000,0.002800,0.392400,1315.00000,0.739800,0.476760,0.541833,0.096644,0.140112,15835.747266,14229.545236
101365,1,5,21.000000,0.033300,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.250900,11985.00000,0.592700,0.319100,0.472340,0.022583,0.069137,41936.911338,24695.074117
101435,1,5,12.000000,0.034500,0.00600,0.005600,0.002800,0.010700,0.013700,0.009100,0.001500,0.100500,10321.00000,0.420700,0.619308,0.652812,0.142857,0.201229,62919.653277,53499.820276
101453,1,5,13.000000,0.017200,0.00000,0.000000,0.000000,0.010500,0.000000,0.000000,0.021100,0.484200,10569.00000,0.580600,0.500000,0.523810,0.096644,0.132706,47149.002148,30423.454545
101462,1,5,12.000000,0.019500,0.00730,0.000000,0.000000,0.016600,0.012900,0.014700,0.007400,0.473300,1471.00000,0.693000,0.476760,0.541833,0.096644,0.044365,20255.119048,15789.673861
101480,1,5,13.000000,0.012400,0.00590,0.000000,0.000000,0.004300,0.008600,0.006600,0.007700,0.200600,6218.00000,0.430800,0.463049,0.518117,0.087077,0.102626,51540.479439,45970.114029
101499,1,5,32.000000,0.006800,0.02030,0.000000,0.000000,0.011500,0.005300,0.016800,0.010600,0.296700,1151.00000,0.551600,0.476760,0.541833,0.096644,0.105263,21057.352645,19450.327820
101505,1,5,12.000000,0.037700,0.01910,0.000000,0.000000,0.005500,0.011000,0.003400,0.005700,0.632000,2814.00000,0.332900,0.470749,0.550607,0.050815,0.097795,44131.908529,34964.113854
101514,1,5,41.000000,0.046100,0.02960,0.000000,0.000000,0.020100,0.019600,0.034700,0.013500,0.618600,3114.00000,0.390900,0.430601,0.516312,0.053065,0.069742,43152.473321,34578.200563
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45891902,13,5,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45891903,13,5,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45891904,13,5,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45891905,13,5,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45891906,13,5,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45891907,13,5,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45891908,13,5,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45896401,45,5,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45896402,45,5,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45897301,48,6,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45897302,48,6,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45897303,48,6,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45897304,48,6,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45897305,48,6,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45897306,48,6,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45897307,48,6,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45897308,48,6,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.299054,0.380569,0.015799,0.067174,27959.910511,23652.171945
45920401,6,8,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.750000,0.541833,0.070302,0.053628,53627.235211,39643.046868
47503301,34,2,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.476760,0.541833,0.096644,0.132706,47149.002148,35894.599976
47503302,22,5,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.476760,0.541833,0.096644,0.132706,47149.002148,35894.599976
47647001,6,8,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.476760,0.541833,0.096644,0.060440,44306.170213,29288.329670
47657701,48,6,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.476760,0.541833,0.096644,0.024055,21691.421053,17064.278351
47657702,48,6,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.476760,0.541833,0.096644,0.024055,21691.421053,17064.278351
47691101,6,8,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.476760,0.541833,0.064433,0.046392,50334.477778,32425.023196
48065701,20,4,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.329630,0.453034,0.044866,0.048735,54484.778660,34389.592284
48154401,39,3,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.476760,0.541833,0.096644,0.132706,72262.406250,37113.368421
48387801,6,8,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.476760,0.541833,0.096644,0.132706,40397.737705,23769.390110
48400201,6,8,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.476760,0.541833,0.013831,0.052559,30390.680000,20044.056708
48414501,48,6,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.476760,0.541833,0.096644,0.132706,24512.909091,18167.007937
48621101,34,2,19.656359,0.165396,0.03487,0.020375,0.008901,0.040883,0.035673,0.015773,0.098882,0.274705,10775.99299,0.521227,0.476760,0.541833,0.096644,0.132706,5426.700000,5961.913793

In [ ]:
### your error was from the fact that you did not give select from model an estimator to work with.  It needs an estimator 
### to run your features through so that it can either look at feature importance or coeffecients.  You also have to make
### sure to use a model that fits the type of Y you have.  In this case you have continuous data so you need a
### model that is a regressor.  If you used a classifier, you would have gotten antoher error.