In [6]:
import pandas as pd

In [4]:
# url link to the csv file for importing college scorecard data
url = 'https://ed-public-download.app.cloud.gov/downloads/Most-Recent-Cohorts-All-Data-Elements.csv'

In [7]:
# reading data into a dataframe 
data = pd.read_csv(url)

C:\Users\harshvardhan\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (6,9,1608,1619,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1688,1689,1690,1691,1692,1703,1704,1725,1726,1727,1728,1729,1743) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [10]:
# checking head of the data
data.head()

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRYP8_FTNFT,OMENRAP8_FTNFT,OMENRUP8_FTNFT,OMACHT6_PTNFT,OMAWDP6_PTNFT,OMACHT8_PTNFT,OMAWDP8_PTNFT,OMENRYP8_PTNFT,OMENRAP8_PTNFT,OMENRUP8_PTNFT
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,www2.aamu.edu/scripts/netpricecalc/npcalc.htm,...,0.0000,0.1727,0.3909,16.0,0.3125,16.0,0.3125,0.0000,0.0000,0.6875
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,...,0.0102,0.2187,0.1385,248.0,0.3589,248.0,0.4032,0.0444,0.2500,0.3024
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.0125,0.4375,0.0000,36.0,0.5000,36.0,0.5278,0.0278,0.4444,0.0000
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.0124,0.3209,0.1242,131.0,0.3588,131.0,0.3664,0.0382,0.4351,0.1603
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,...,0.0000,0.3672,0.1977,36.0,0.2778,36.0,0.3056,0.0278,0.5833,0.0833

In [12]:
# visually inspecting the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7593 entries, 0 to 7592
Columns: 1805 entries, UNITID to OMENRUP8_PTNFT
dtypes: float64(504), int64(13), object(1288)
memory usage: 104.6+ MB

In [14]:
data.describe()

,UNITID,OPEID,OPEID6,SCH_DEG,HCM2,MAIN,NUMBRANCH,PREDDEG,HIGHDEG,CONTROL,...,OMENRYP8_FTNFT,OMENRAP8_FTNFT,OMENRUP8_FTNFT,OMACHT6_PTNFT,OMAWDP6_PTNFT,OMACHT8_PTNFT,OMAWDP8_PTNFT,OMENRYP8_PTNFT,OMENRAP8_PTNFT,OMENRUP8_PTNFT
count,7.593000e+03,7.593000e+03,7593.000000,7286.00000,7593.000000,7593.000000,7593.000000,7593.000000,7593.000000,7593.000000,...,3671.000000,3671.000000,3671.000000,3955.000000,2948.000000,3955.000000,2947.000000,2947.000000,2947.000000,2947.000000
mean,1.765726e+06,1.910166e+06,16441.276307,1.89720,0.009219,0.738312,7.185566,1.810088,2.202292,2.192282,...,0.008412,0.169805,0.260487,158.747914,0.368262,158.705689,0.386980,0.016495,0.207125,0.389400
std,6.771661e+06,3.516382e+06,14088.868371,0.87879,0.095578,0.439583,21.184166,1.031903,1.318152,0.835941,...,0.035949,0.175972,0.206629,701.589333,0.234315,701.556552,0.235768,0.054862,0.209142,0.251564
min,1.006540e+05,1.002000e+05,1002.000000,1.00000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.752630e+05,3.402000e+05,3395.000000,1.00000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,...,0.000000,0.002650,0.102150,0.000000,0.203250,0.000000,0.222200,0.000000,0.000000,0.210600
50%,2.318730e+05,1.054211e+06,10490.000000,2.00000,0.000000,1.000000,1.000000,2.000000,2.000000,2.000000,...,0.000000,0.132500,0.214300,24.000000,0.346800,24.000000,0.369600,0.000000,0.176500,0.345000
75%,4.496120e+05,3.010617e+06,26092.000000,3.00000,0.000000,1.000000,3.000000,3.000000,4.000000,3.000000,...,0.008300,0.265400,0.375000,116.000000,0.500350,115.500000,0.528100,0.016700,0.332200,0.521700
max,4.862110e+07,8.209884e+07,42542.000000,3.00000,1.000000,1.000000,135.000000,4.000000,4.000000,3.000000,...,0.940300,1.000000,1.000000,33078.000000,1.000000,33078.000000,1.000000,1.000000,1.000000,1.000000

In [67]:
# Several values in the columns are represented as PrivacySuppressed: replacing them with NULL
data = data.replace('PrivacySuppressed', 'NULL')

In [95]:
#Calculating percentage of NULL data in each column and selecting those that have less than 5% NULL values
columns_2 = data.isnull().sum()/data.shape[0]*100 < 5

In [96]:
columns_2

UNITID                          True
OPEID                           True
OPEID6                          True
INSTNM                          True
CITY                            True
STABBR                          True
ZIP                             True
ACCREDAGENCY                   False
INSTURL                         True
NPCURL                         False
SCH_DEG                         True
HCM2                            True
MAIN                            True
NUMBRANCH                       True
PREDDEG                         True
HIGHDEG                         True
CONTROL                         True
ST_FIPS                         True
REGION                          True
LOCALE                         False
LATITUDE                       False
LONGITUDE                      False
CCBASIC                        False
CCUGPROF                       False
CCSIZSET                       False
HBCU                           False
PBI                            False
ANNHI                          False
TRIBAL                         False
AANAPII                        False
                               ...
COUNT_WNE_P9                   False
MN_EARN_WNE_P9                 False
SD_EARN_WNE_P9                 False
GT_25K_P9                      False
DEBT_MDN_SUPP                   True
GRAD_DEBT_MDN_SUPP              True
GRAD_DEBT_MDN10YR_SUPP          True
RPY_3YR_RT_SUPP                False
LO_INC_RPY_3YR_RT_SUPP         False
MD_INC_RPY_3YR_RT_SUPP         False
HI_INC_RPY_3YR_RT_SUPP         False
COMPL_RPY_3YR_RT_SUPP          False
NONCOM_RPY_3YR_RT_SUPP         False
DEP_RPY_3YR_RT_SUPP            False
IND_RPY_3YR_RT_SUPP            False
PELL_RPY_3YR_RT_SUPP           False
NOPELL_RPY_3YR_RT_SUPP         False
FEMALE_RPY_3YR_RT_SUPP         False
MALE_RPY_3YR_RT_SUPP           False
FIRSTGEN_RPY_3YR_RT_SUPP       False
NOTFIRSTGEN_RPY_3YR_RT_SUPP    False
ICLEVEL                         True
UGDS_MEN                       False
UGDS_WOMEN                     False
CDR3_DENOM                     False
CDR2_DENOM                     False
T4APPROVALDATE                 False
D_PCTPELL_PCTFLOAN             False
OPENADMP                       False
ACCREDCODE                     False
Length: 1582, dtype: bool

In [97]:
data.loc[:,columns_2].shape

(7593, 99)